[package]
name = "lunokod"
version = "0.1.0"
authors = ["senet4er <senet4er@gmail.com>"]

[dependencies]
chrono = "0.4"
diesel = { version = "1.3", features = ["chrono", "sqlite"] }
failure = "0.1"
tera = "0.11"
warp = "0.1"
